name: "audit repository"

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "20 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Evaluate repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh repo list -L 300 --json name,owner,isPrivate > output.json
      - uses: docker://ghcr.io/m-mizutani/opaq:v0.1.0
        with:
          args: "-u https://opa-server-h6tk4k5hyq-an.a.run.app/v1/data/github/fail -i output.json --fail-defined"
      - name: notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
